resource_group_name = "vam-rg-newP"
location            = "West US 2"
app_service_plan_name = "prod-plan"
web_app_name        = "prod-web-app"
sku_size            = "B1"
os_type             = "Windows"
