resource_group_name = "vam-rg-terra"
location            = "West US 2"
app_service_plan_name = "dev-plan-terra"
web_app_name        = "dev-web-terra"
sku_size            = "B1"
os_type             = "Windows"
